version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teamcity
      MYSQL_DATABASE: teamcity
    volumes:
    - db-data:/var/lib/mysql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  teamcity:
    image: jetbrains/teamcity-server
    container_name: teamcity-server-instance
    volumes:
    - data:/var/lib/mysql/data/teamcity_server/datadir
    - logs:/opt/teamcity/logs
    ports:
    - 8111:8111
    links:
      - db
    depends_on:
      - db
      
volumes:
  db-data:
  data:
  logs:
  
