version: '3.1'
services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: teamcity@123PW
    volumes:
    - db-data:/var/lib/postgresql/data
 
  teamcity:
    image: jetbrains/teamcity-server
    container_name: teamcity-server-instance
    volumes:
    - data:/data/teamcity_server/datadir
    - logs:/opt/teamcity/logs
    ports:
    - 8111:8111
    links:
      - postgresql
    depends_on:
      - postgresql
      
volumes:
  db-data:
  data:
  logs:
  
